name: 🐛 Bug Report
description: Report a reproducible bug in simple-conventional-release.
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 🛠 Steps to Reproduce
      description: How can this bug be reproduced?
      placeholder: |
        1. Run `...`
        2. Execute `...`
        3. See the error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: ❌ Actual Behavior
      description: What is happening instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 📦 Version
      description: What version of the package are you using?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📜 Logs & Screenshots
      description: If applicable, add logs or screenshots to help explain the issue.
    validations:
      required: false
